### ISSUE TITLE
SyntaxError: invalid syntax on windows 10

### ISSUE THREAD

**Issue by Oguangpan** [sciter-sdk/pysciter#16]
Os: windows10 X64
Python version: 3.7.0b3 on win32
Sciter.dll version: win32
pysciter version: 0.4.23

When I import sciter, python prompts me: "SyntaxError: invalid syntax"

error code:
```
>>> import sciter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Pan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pysciter-0.4.23-py3.7.egg\sciter\__init__.py", line 23, in <module>
    from .window import Window
  File "C:\Users\Pan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pysciter-0.4.23-py3.7.egg\sciter\window.py", line 5, in <module>
    import sciter.host
  File "C:\Users\Pan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pysciter-0.4.23-py3.7.egg\sciter\host.py", line 10, in <module>
    import sciter.dom
  File "C:\Users\Pan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pysciter-0.4.23-py3.7.egg\sciter\dom.py", line 504
    def send_request(self, url: str, params=None, method='GET', async=False, data_type=SciterResourceType.RT_DATA_HTML):
                                                                    ^
SyntaxError: invalid syntax
```

Sorry, I can't find the wrong place

**Comment by pravic** [comment]
It looks like `async` is a keyword now. I'll fix it.

**Comment by pravic** [comment]
Can you check it now?

**Comment by Oguangpan** [comment]
I am sorry for the delay in responding to you. 
Because I'm on the back of the earth 😁 

The problem is gone
Thank you.

**Comment by pravic** [comment]
Ok.
