### ISSUE TITLE
py27 not been supported

### ISSUE THREAD

**Issue by waleson** [sciter-sdk/pysciter#17]
python27 not supported

pip install pysciter

Traceback (most recent call last):
  File "examples/minimal.py", line 3, in <module>
    import sciter
  File "E:\tools\Python27\lib\site-packages\sciter\__init__.py", line 18, in <module>
    from .capi.scapi import SciterAPI
  File "E:\tools\Python27\lib\site-packages\sciter\capi\scapi.py", line 5, in <module>
    from sciter.capi.scdef import *
  File "E:\tools\Python27\lib\site-packages\sciter\capi\scdef.py", line 182
    def __init__(self, string_type: str):
                                  ^
SyntaxError: invalid syntax

**Comment by pravic** [comment]
Yes, that's true. It is mentioned in the readme.

Not that so much to do to support it, just it happened that I don't like 2.x and don't want to bother to support it.

**Comment by waleson** [comment]
thank you. after installed the latest python 3.6.5 ,it  worked.
