### ISSUE TITLE
Error: 196608 is not a valid PHASE_MASK

### ISSUE THREAD

**Issue by nowayout** [sciter-sdk/pysciter#61]
In the html file use
`<input type="date" name="date1" value="2021-12-06" />`
when select other date, it show errors:
Exception ignored on calling ctypes callback function: <bound method EventHandler._element_proc of <__main__.Frame object at 0x01D787A8>>
Traceback (most recent call last):
  File "D:\pypqj\sciter\event.py", line 252, in _element_proc
    phase = PHASE_MASK(m.cmd & 0xFFFFF000)
  File "C:\Python39\lib\enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "C:\Python39\lib\enum.py", line 702, in __new__
    raise ve_exc
ValueError: 196608 is not a valid PHASE_MASK

**Comment by pravic** [comment]
Well, obviously it's not a phase mask. I woonder, what that date control tries to send.

**Comment by nowayout** [comment]
Such as, now is 2021-12-06, change the date to: 2021-12-08 or 2021-12-01
