### ISSUE TITLE
plain-win.py says ctypes.ArgumentError: argument 4: <class 'OverflowError'>: int too long to convert

### ISSUE THREAD

**Issue by retsyo** [sciter-sdk/pysciter#69]
I tested `plain-win.py` on windows 10 64bits, both 
`Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32`
and
`Python 3.6.10 |Anaconda custom (64-bit)| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)] on win32`
but I get
```
WndProc exception: 1050D7A, 0x0024, 0x0, 0x2DFADEE3D0
Traceback (most recent call last):
  File "plain-win.py", line 86, in on_wnd_message
    return windll.user32.DefWindowProcW(hWnd, Msg, wParam, lParam)
ctypes.ArgumentError: argument 4: <class 'OverflowError'>: int too long to convert
WndProc exception: 1050D7A, 0x0081, 0x0, 0x2DFADEE380
Traceback (most recent call last):
  File "plain-win.py", line 86, in on_wnd_message
    return windll.user32.DefWindowProcW(hWnd, Msg, wParam, lParam)
ctypes.ArgumentError: argument 4: <class 'OverflowError'>: int too long to convert
Failed to create window:  0
```

btw, `minimal.py` runs ok

**Comment by pravic** [comment]
Thanks for the catch!
